#!/bin/bash
#check if a search string has been specified
numargs=$#
if [ $numargs -lt 1 ]
then
echo # new line seperator
echo "search string not specified"
exit 1
fi

#generate the log file
sstring=$1 #search string
count=0
Limit=30

while ["$count" lt "Limit" ]
#
#spaces, because these are "test-brakets"....
do
datestr='date +%s' #generate date string for files
touch"log_$datestr.txt"
uname >> log_$datestr.txt
log >> log_$datestr.txt
grep -m 'expr $count +1' $string word.txt | tail -1 >> log_$datestr.txt
sleep 15 # wait for 10 seconds
count= 'expr $count + 1'
done # while
echo
exit 0
